org: informatik
app: umfragetool
service: rest-api-example
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  example:
    handler: handler.example
    events:
      - httpApi:
          path: /
          method: get
