stages:
  - test

test:
  image: python:3.9
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest
  artifacts:
    when: always
    reports:
      junit: pytest.xml
    paths:
      - pytest.xml
