stages:
  - test
test:
  image: python:3.9
  stage: test
  before_script: 
  script:
     - export DATABASE_URL="doesnotmatter" && cd backend/services/rest-apis && pip install -r requirements.txt && pytest