stages:
  - test
test:
  image: python:3.9
  stage: test
  before_script: 
  script:
     - export DATABASE_URL=mysql://root:password@localhost:3306/mydatabase && cd backend/services/rest-apis && pip install -r requirements.txt && pytest
