export const FETCH_SURVEY_REQUEST = 'FETCH_SURVEY_REQUEST';
export const FETCH_SURVEY_SUCCESS = 'FETCH_SURVEY_SUCCESS';
export const FETCH_SURVEY_FAILURE = 'FETCH_SURVEY_FAILURE';

export const SAVE_QUESTION_ANSWERS_REQUEST = 'SAVE_SURVEY_REQUEST';
export const SAVE_QUESTION_ANSWERS_SUCCESS = 'SAVE_SURVEY_SUCCESS';
export const SAVE_QUESTION_ANSWERS_FAILURE = 'SAVE_SURVEY_FAILURE';

export const SAVE_SURVEY_SCORES = 'SAVE_SURVEY_SCORES';
