export const FETCH_SURVEY_REQUEST = 'FETCH_SURVEY_REQUEST';
export const FETCH_SURVEY_SUCCESS = 'FETCH_SURVEY_SUCCESS';
export const FETCH_SURVEY_FAILURE = 'FETCH_SURVEY_FAILURE';

export const SUBMIT_SURVEY_REQUEST = 'SUBMIT_SURVEY_REQUEST';
export const SUBMIT_SURVEY_SUCCESS = 'SUBMIT_SURVEY_SUCCESS';
export const SUBMIT_SURVEY_FAILURE = 'SUBMIT_SURVEY_FAILURE';